### PR TITLE
#164325789 Add JWT authentication on swagger.

### PR DESCRIPTION
**Pull request by katherine95**
#### What does this PR do?
Has JWT authentication on swagger enabled.
#### Description of Task to be completed?
- Downgrade `django-rest-swagger` to version `2.1.2`.
- Document all endpoints.
- Enable JWT authentication on swagger.
- Test protected endpoints on swagger.
#### How should this be manually tested?
1. Clone this repo.
   `git clone https://github.com/jkamz/ireporter.git`
2. Fetch all origin to get all branches
   `git fetch origin`
3. Checkout to `ch-swagger-jwt-authentication-164325789` branch.
   `git checkout ch-swagger-jwt-authentication-164325789`
4. Activate `virtualenv`
    `$ virtualenv -p python .venv`
    `$ source .venv/bin/activate`
5. Install requirements
   `$ pip install -r requirements.txt`
6. Start server
   `$ python api/manage.py runserver`
7. Test the endpoint on postman in the following steps:
      - `/api/ireporter/docs`
#### What are the relevant pivotal tracker stories?
[#164325789](https://www.pivotaltracker.com/story/show/164325789)
#### Screenshot
image
image

### CODE REVIEW

**Review by jkamz — CHANGES_REQUESTED** [review]
Looks good. Could you please upgrade the django version to 2.1.7 in pipfile and pipfile.lock?

**Comment by katherine95** [comment]
> Looks good. Could you please upgrade the django version to 2.1.7 in pipfile and pipfile.lock?

Thank you. I have worked on it

**Comment by AlvinMugambi** [comment]
Looks good

**Comment by ElishaMisoi** [comment]
Tested it, seems to be working fine 👍🏽

**Pull request merged**
