### PR TITLE
#164271765 Add coverage and maintainability services

### PR DESCRIPTION
**Pull request by jkamz**
### What does this PR do?
This PR integrates coverage and maintainability services to ensure code quality

### Description of the tasks to be completed
- Integrate Coveralls
- Integrate Code Climate
- Include badges in README

### How can this be manually tested?
 - View the coverage integration [here](https://coveralls.io/github/jkamz/ireporter)
- View code climate integration [here](https://codeclimate.com/github/jkamz/ireporter)

### What are the relevant Pivotal Tracker stories?
[#164271765](https://www.pivotaltracker.com/story/show/164271765)

### CODE REVIEW

**Comment by Benkimeric** [comment]
Nice job

**Comment by katherine95** [comment]
Add the PT story in the format [#story-id](story-link).

**Comment by jkamz** [comment]
> Add the PT story in the format `[#story-id](story-link)`
> When describing how to manually test give steps of how one can see the change you made in action.

Thanks for the input. Please review the changes.

**Comment by Siffersari** [comment]
Everything seems in order. Good job

**Pull request merged**
