### PR TITLE
#164326073 Fix password rematch validation.

### PR DESCRIPTION
**Pull request by katherine95**
#### What does this PR do?
Validate password rematch during resetting password and refactor tests.
#### Description of Task to be completed?
Validate password rematch at `/api/auth/reset_password_confirm/` url and refactor tests for the endpoint.
#### How should this be manually tested?
1. Clone this repo.
   `git clone https://github.com/jkamz/ireporter.git`
2. Fetch all origin to get all branches
   `git fetch origin`
3. Checkout to `ft-reset-password-email-164326073` branch.
   `git checkout ft-reset-password-email-164326073`
4. Activate `virtualenv`
    `$ virtualenv -p python .venv`
    `$ source .venv/bin/activate`
5. Install requirements
   `$ pip install -r requirements.txt`
6. Start server
   `$ python api/manage.py runserver`
7. Test the endpoint on postman in the following steps:
      - `POST /api/auth/signup/`
      - `POST /api/auth/activate/`
      - `POST /api/auth/reset_password/`
      -  `PATCH /api/auth/reset_password_confirm/?uid=string_uid&token=generated_token`
      - Enter passwords that don't match to test the endpoint.
8. Run tests:
   `$ python api/manage.py test`
#### What are the relevant pivotal tracker stories?
[#164326073](https://www.pivotaltracker.com/story/show/164326073)
#### Screenshot
image
image
image

### CODE REVIEW

**Review by AlvinMugambi — CHANGES_REQUESTED** [review]
You can return a JSON response on successful password reset instead of a string.

**Comment by katherine95** [comment]
> You can return a JSON response on successful password reset instead of a string.

It doesn't make any difference when rendering the response. I will return it as a JsonResponse though.
Thanks for feedback

**Review by Siffersari — COMMENTED** [review]
Good job. A suggestion would be,  include the type of method that we are using to make the requests. 

For example: 'POST /api/auth/signup/'

**Comment by katherine95** [comment]
> Good job. A suggestion would be, include the type of method that we are using to make the requests.
> 
> For example: 'POST /api/auth/signup/'

Done. Thanks for the suggestion

**Review by meshack-mbuvi — CHANGES_REQUESTED** [review]
When updating any record, the method should be `put` not `post`

**Comment by katherine95** [comment]
> When updating any record, the method should be `put` not `post`

Thanks changes made.

**Comment by katherine95** [comment]
> > You can return a JSON response on successful password reset instead of a string.
> 
> It doesn't make any difference when rendering the response. I will return it as a JsonResponse though.
> Thanks for feedback

I got your point. thanks I just corrected it.

**Comment by katherine95** [comment]
> When updating any record, the method should be `put` not `post`

Updated it `patch`

**Review by AlvinMugambi — APPROVED** [review]

**Pull request closed without merging**
