### PR TITLE
#164397757 A user should be able to create an intervention.

### PR DESCRIPTION
**Pull request by Benkimeric**
#### What does this PR do?
Adds create Intervention endpoint
#### Description of Task to be completed?
- Add create intervention endpoint
- Add tests for creating an intervention record
- Validate fields in creating intervention record
#### How should this be manually tested?
Step 1

Navigate to your working directory, create and activate the virtual environment

```$ virtualenv -p python venv```

```$ source venv/bin/activate```

Clone the repository

```$ git clone https://github.com/ann-mukundi/ireporter.git```

Switch to testing branch

```$ git checkout ft-create-interventions-164397757```

Switch to the ireporter directory

```$ cd ireporter/```

Install project dependencies

```$ pip install -r requirements.txt```

Run the database migrations

```$ python manage.py makemigrations interventions```
```$ python manage.py migrate```

Step 2
**Running the application**

```$ python manage.py runserver```

Step 3
**Login user**
Signup and activate user (if no user exists)
```POST:<your-localhost>/api/auth/signup```

Login user (after activation)
```POST:<your-localhost>/api/auth/login```

Step 4
**Add Intervention**
Use the token provided after login for Authorization and the endpoint
```POST<your-localhost>/api/interventions/```
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
[#164397757 ](https://www.pivotaltracker.com/story/show/164397757)
#### Screenshots (if appropriate)
Screenshots:
**Success**
Screenshot from 2019-03-14 13-54-49

**Validation**
**Duplicate Intervention Title By same user**
Screenshot from 2019-03-14 13-58-12
#### Questions:
None

### CODE REVIEW

**Review by jkamz — CHANGES_REQUESTED** [review]
This looks really good. Since you have added coveralls to the requirements.txt file, can you update the Travis.yml so that coveralls is not installed separately? (coveralls will be installed with other packages in the requirements files so we no longer need to install it separately. We only need to pip install requirements.txt)

**Review by AlvinMugambi — COMMENTED** [review]
Looks good.

**Review by Siffersari — CHANGES_REQUESTED** [review]
You could include an extra line at the end of the model, views, tests, and serializer files in line with PEP8 standards.

Just as good practice. You could also include extra screenshots displaying other outcomes such as input of incorrect payload or validation of duplicate intervention records. 

This makes it easier to steal a glance at the functionality that comes with the endpoint.

**Comment by Benkimeric** [comment]
> You could include an extra line at the end of the model, views, tests, and serializer files in line with PEP8 standards.
> 
> Just as good practice. You could also include extra screenshots displaying other outcomes such as input of incorrect payload or validation of duplicate intervention records.
> 
> This makes it easier to steal a glance at the functionality that comes with the endpoint.

For pep 8 extra line, I have already implemented only that GitHub does not display it. You can confirm by even checking previous PRs even the latest one you have created. For screenshots, I will add more right now.

**Comment by Benkimeric** [comment]
> This looks really good. Since you have added coveralls to the requirements.txt file, can you update the Travis.yml so that coveralls is not installed separately? (coveralls will be installed with other packages in the requirements files so we no longer need to install it separately. We only need to pip install requirements.txt)

@jkamz Look keenly, I did not add coveralls to the requirements.txt but only coverage. So for `travis.yml` it is still okay to install coveralls from the travis file configurations.

**Review by jkamz — APPROVED** [review]

**Comment by Elisha-Misoi** [comment]
I noticed that you separated the interventions from the redflags... Since the incident serializer is the same... You can just use the same folder for interventions as well, because we will end up having so many

**Review by Siffersari — APPROVED** [review]
Good job

**Comment by meshack-mbuvi** [comment]
The PR is not formated correctly

**Comment by katherine95** [comment]
> The PR is not formated correctly

Format the relevant pivotal tracker story properly. You can use https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices for reference

**Comment by Benkimeric** [comment]
> The PR is not formated correctly

**Comment by Benkimeric** [comment]
> The PR is not formated correctly

I have resolved this issue

**Pull request merged**
